# Shopping List
shopping_lists_create:
    path: /shopping-lists
    controller: App\Controller\ShoppingListsController::create
    methods: POST|OPTIONS

shopping_lists_read_all:
    path: /shopping-lists
    controller: App\Controller\ShoppingListsController::readAll
    methods: GET|HEAD

shopping_lists_read:
    path: /shopping-lists/{id}
    controller: App\Controller\ShoppingListsController::read
    methods: GET|HEAD
